--完整性约束条件：
--测试主键
CREATE TABLE IF NOT EXISTS user1(
id INT PRIMARY KEY,--或者key
username VARCHAR(20)
);
--查看创建表的定义
SHOW CREATE TABLE user1;

INSERT user1 VALUES(1,'KING');
INSERT user1 VALUES(2,'QUEEN');

--测试自增长
CREATE TABLE IF NOT EXISTS user2(
id SMALLINT KEY AUTO_INCREMENT,
username VARCHAR(20)
);

INSERT user2(username) VALUES('WING');
INSERT user2 VALUES(122,'KING');
INSERT user2(username) VALUES('WING1');
INSERT user2 VALUES(NULL,'KING2');
INSERT user2 VALUES(DEFAULT,'KING3');

CREATE TABLE IF NOT EXISTS user3(
id SMALLINT KEY AUTO_INCREMENT,
username VARCHAR(20)
)AUTO_INCREMENT=100;
--修改自增长的值
ALTER TABLE user3 AUTO_INCREMENT=200;


--非空约束
CREATE TABLE IF NOT EXISTS user4(
id INT UNSIGNED KEY AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
password CHAR(32) NOT NULL,
age TINYINT UNSIGNED
);

INSERT user4(username,password) VALUES('kon','jif');

--默认值
CREATE TABLE IF NOT EXISTS user5(
id INT UNSIGNED KEY AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
password CHAR(32) NOT NULL,
age TINYINT UNSIGNED DEFAULT 18,
addr VARCHAR(50) NOT NULL DEFAULT '北京',
sex ENUM('MALE','FEMALE','NONE') NOT NULL DEFAULT 'MALE'
);

INSERT user5(username,password) VALUES('KING','KING');

--UNIQUE可以有很多个，主键只能一个

-- 建表的一般类型
-- CREATE TABLE [IF NOT EXISTS] tb_name(
-- 字段名称 字段类型 UNSIGNED|ZEROFILL NOT NULL DEFAULT 默认值 PRIMARY UNIQUE AUTO_INCREMENT
-- )ENGINE=INNODB CHARSET=UTF8 AUTO_INCREMENT=100;

--创建用户表
CREATE TABLE IF NOT EXISTS user6(
id SMALLINT UNSIGNED KEY AUTO_INCREMENT,
username VARCHAR(20) NOT NULL UNIQUE,
password CHAR(32) NOT NULL,
email VARCHAR(50) NOT NULL DEFAULT '834153554@QQ.com',
age TINYINT UNSIGNED DEFAULT 18,
addr VARCHAR(200) NOT NULL DEFAULT '北京',
salary FLOAT(6,2),
sex ENUM('MALE','FEMALE','NONE') NOT NULL DEFAULT 'MALE'
);

--重命名
--ALTER TABLE user6 RENAME TO user7;
--ALTER TABLE user6 RENAME AS user7;
--ALTER TABLE user6 RENAME user7;
--RENAME TABLE user6 TO user7;

--添加card
ALTER TABLE user7 ADD card CHAR(18);
ALTER TABLE user7 ADD test1 VARCHAR(10) NOT NULL UNIQUE;
ALTER TABLE user7 ADD test2 VARCHAR(20) NOT NULL FIRST;
ALTER TABLE user7 ADD test3 VARCHAR(20) NOT NULL AFTER username;

--一次添加多个
ALTER TABLE user7
ADD test4 INT(20) NOT NULL AFTER username,
ADD test5 FLOAT(20) NOT NULL AFTER age,
ADD test6 SET('A','B');

--删除字段
ALTER TABLE user7 DROP card;
ALTER TABLE user7

DROP test2,
DROP test3,
DROP test4,
DROP test5,
DROP test6;

--添加test字段，删除addr字段
ALTER TABLE user7

ADD test INT UNSIGNED NOT NULL DEFAULT 10 AFTER sex,

DROP addr;
--将email字段VARCHAR(200)
ALTER TABLE user7 MODIFY email VARCHAR(200);
ALTER TABLE user7 MODIFY email VARCHAR(50) NOT NULL DEFAULT '834153554@QQ.com';
--移动

ALTER TABLE user7 MODIFY age CHAR(18) AFTER email;

ALTER TABLE user7 CHANGE test test1 CHAR(18) NOT NULL AFTER email;
ALTER TABLE user7 CHANGE test1 test CHAR(200) NOT NULL AFTER age;
-- 添加删除默认值
ALTER TABLE user7 ALTER age SET DEFAULT 18;
ALTER TABLE user7 ALTER age DROP DEFAULT;

--添加删除主键

CREATE TABLE IF NOT EXISTS user8(
id INT UNSIGNED AUTO_INCREMENT,
);
ALTER TABLE user8 ADD PRIMARY KEY (id);--也可以添加复合主键
ALTER TABLE user8 ADD card CHAR(18);
ALTER TABLE user8 ADD CONSTRAINT symbol PRIMARY KEY index_type(id);

ALTER TABLE user8 DROP PRIMARY KEY;
--修改表的存储引擎
ALTER TABLE user8 ENGINE=MyISAM;
