-- 创建普通索引
CREATE TABLE TEST1(
id TINYINT UNSIGNED,
username VARCHAR(20),
INDEX in_id(id),
KEY in_username(username)
);
-- 创建唯一索引
CREATE TABLE TEST2(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
username VARCHAR(20) NOT NULL UNIQUE,
card CHAR(18) NOT NULL,
UNIQUE KEY uni_card(card)
);
-- 创建全文索引
CREATE TABLE TEST3(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
username VARCHAR(20) NOT NULL UNIQUE,
card CHAR(18) NOT NULL,
FULLTEXT INDEX full_card(card)
);

-- 创建单列索引
CREATE TABLE TEST4(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
test1 VARCHAR(20) NOT NULL,
test2 VARCHAR(20) NOT NULL,
test3 VARCHAR(20) NOT NULL,
test4 VARCHAR(20) NOT NULL,
INDEX in_test1(test1)
);
-- 创建多列索引
CREATE TABLE TEST5(
id TINYINT UNSIGNED AUTO_INCREMENT KEY,
test1 VARCHAR(20) NOT NULL,
test2 VARCHAR(20) NOT NULL,
test3 VARCHAR(20) NOT NULL,
test4 VARCHAR(20) NOT NULL,
INDEX mul_t1_t2_t3_t4(test1,test2,test3,test4)
);

--删除索引
DROP INDEX in_id ON TEST1;
ALTER TABLE TEST1 DROP INDEX in_username(username);

-- 添加索引
CREATE INDEX in_id ON TEST1(id);

ALTER TABLE TEST1 ADD INDEX in_username(username);
